### ISSUE TITLE
overwrite flash content

### ISSUE THREAD

**Issue by EmbeddedAndMore** [tegesoft/flash-stm32f407#1]
hi

first of all thank you for this amazing job.

i can easily read from and write into flash in my stm32f4 discovery board , but in flash , i nead to change 50 bytes at runtime , but it seems it's not possible, i suppose ,i should erase whole sector just for overwrite 50 bytes and of course it takes time, is there any possibility to overwrite these value without erasing whole sector ??

thanks in advance

**Comment by LaurentGomila** [comment]
> is there any possibility to overwrite these value without erasing whole sector ??

No, this is how flash memory works.

**Comment by delaitre** [comment]
Closing as there is nothing we can do. As Laurent said, that's how flash memory works!
